/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BulletinBoard: typeof import('./src/components/bulletinBoard/bulletinBoard.vue')['default']
    copy: typeof import('./src/components/httpConfig/IotSocket copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    IconTextList: typeof import('./src/components/menuView/iconTextList.vue')['default']
    IotSocket: typeof import('./src/components/httpConfig/IotSocket.vue')['default']
    'IotSocket copy': typeof import('./src/components/httpConfig/IotSocket copy.vue')['default']
    LeftMenuView: typeof import('./src/components/menuView/leftMenuView.vue')['default']
    PenList: typeof import('./src/components/menuView/penList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
